CREATE DATABASE SALES;

CREATE TABLE PRODUCT (
	ID BIGSERIAL NOT NULL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(255),
	PRICE NUMERIC(16,2),
	SKU VARCHAR(20),
	DATE_REGISTER DATE
);

CREATE TABLE customer (
	id bigserial not null primary key,
	birth date not null,
	name varchar(100) not null,
	adress varchar(255) not null,
	ru varchar(14) not null,
	phone varchar(14),
	email varchar(100),
	date_register date
);

CREATE TABLE SALE (
	ID BIGSERIAL NOT NULL PRIMARY KEY,
	ID_CUSTOMER BIGINT REFERENCES CUSTOMER (ID) NOT NULL,
	PAYMENT_METHOD VARCHAR(8) CHECK ( PAYMENT_METHOD IN ('MONEY', 'CARD')) NOT NULL,
	TOTAL NUMERIC(16,2) NOT NULL,
	DATE_SALE TIMESTAMP DEFAULT NOW()
);

CREATE TABLE ITEM_SALE (
	ID BIGSERIAL NOT NULL PRIMARY KEY,
	ID_SALE BIGINT REFERENCES SALE (ID) NOT NULL,
	ID_PRODUCT BIGINT REFERENCES PRODUCT (ID) NOT NULL,
	AMOUNT INTEGER NOT NULL
);
